version: "3.9"
services:
  back-end-1:
    image: holbertonschool/softy-pinko:task5
    networks:
      - back-end-network

  back-end-2:
    image: holbertonschool/softy-pinko:task5
    networks:
      - back-end-network

  front-end:
    image: holbertonschool/softy-pinko:task5
    ports:
      - "80:80"
    networks:
      - back-end-network

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - back-end-1
      - back-end-2
      - front-end
    networks:
      - back-end-network

networks:
  back-end-network:
