version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "9000:80"
  backend:
    build: ./backend
    ports:
      - "5252:5252"
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
